#ifndef BUTTON_MAPPING_H
#define BUTTON_MAPPING_H

#define TETRIS_LEFT_BUTTON_GPIO	18
#define TETRIS_DOWN_BUTTON_GPIO	19
#define TETRIS_RIGHT_BUTTON_GPIO	20
#define TETRIS_ROTATE_90_DEGREE_BUTTON_GPIO	21

#define FALLING_PIECE_FALL_TIMEOUT_MS  1000

#endif